version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    groups:
      security-patches:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: "fix(deps)"
